### ISSUE TITLE
Tracking goals for package dev

### ISSUE THREAD

**Issue by VLucet** [LandSciTech/pfocal#9]
- [x] Clean up all current checks issues in #1 
- [ ] #18
- [x] Add CI with GA
- [x] Add a readme
- [x] Add logo ?
- [x] Use pkgdown website for doc
- [x] #21
- [x] #19
